indentation via spaces and code alignment purge

diff --git a/cert-maintenance b/cert-maintenance
--- a/cert-maintenance
+++ b/cert-maintenance
@@ -18,13 +18,13 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 usage() {
-  err "usage:
+	err "usage:
 ${0##*/} [domain name] [daemon(s) to reload] ...
 
 Only the domain name is strictly necessary. If only the domain name is
@@ -45,55 +45,55 @@ The full chain certificate must be located at '/etc/ssl/example.com.pem'."
 #
 # $1 is a chosen domain name.
 cert_maintenance() {
-  if [ -f '/etc/acme-client.conf' ]; then
-    acme-client -- "$1" >/dev/null
+	if [ -f '/etc/acme-client.conf' ]; then
+		acme-client -- "$1" >/dev/null
 
-  else
-    err "acme-client.conf(5) wasn't found."
+	else
+		err "acme-client.conf(5) wasn't found."
 
-  fi
+	fi
 
-  if [ -f "/etc/ssl/$1.pem" ]; then
-    # if your provider supports the use of OCSP nonces, don't use -N
-    ocspcheck -No "/etc/ssl/$1.ocsp" -- "/etc/ssl/$1.pem" >/dev/null
+	if [ -f "/etc/ssl/$1.pem" ]; then
+		# if your provider supports the use of OCSP nonces, don't use -N
+		ocspcheck -No "/etc/ssl/$1.ocsp" -- "/etc/ssl/$1.pem" >/dev/null
 
-  else
-    err "/etc/ssl/$1.pem wasn't found."
+	else
+		err "/etc/ssl/$1.pem wasn't found."
 
-  fi
+	fi
 }
 
 
 # reload daemons if enabled.
 reload_daemons() {
-  for daemon in "$@"; do
+	for daemon in "$@"; do
 
-    if [ "$(rcctl get "${daemon}" flags)" != 'NO' ]; then
-      rcctl reload "${daemon}"
+		if [ "$(rcctl get "${daemon}" flags)" != 'NO' ]; then
+			rcctl reload "${daemon}"
 
-    # We want to notify the user when a daemon wasn't reloaded.
-    else
-      printf '%s\n' "Unable to reload ${daemon} because it is not enabled." >&2
-      continue
+		# We want to notify the user when a daemon wasn't reloaded.
+		else
+			printf '%s\n' "Unable to reload ${daemon} because it is not enabled." >&2
+			continue
 
-    fi
+		fi
 
-  done
+	done
 }
 
 
 case "$1" in
-  ''|'-h') usage ;;
+	''|'-h') usage ;;
 esac
 
 [ "$(id -u)" -eq 0 ] || err "Execute ${0##*/} with root privileges."
 
 
 if cert_maintenance "$1"; then
-  shift
-  [ -n "$*" ] && reload_daemons "$@" >/dev/null
+	shift
+	[ -n "$*" ] && reload_daemons "$@" >/dev/null
 
 else
-  err 'Unable to perform certificate maintenance.'
+	err 'Unable to perform certificate maintenance.'
 
 fi
diff --git a/genblock b/genblock
--- a/genblock
+++ b/genblock
@@ -18,13 +18,13 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 usage() {
-  err "${0##*/} generates blocklists for unwind(8) and unbound(8) on OpenBSD.
+	err "${0##*/} generates blocklists for unwind(8) and unbound(8) on OpenBSD.
 
 usage: ${0##*/} /path/to/save/blocklist"
 }
@@ -37,18 +37,18 @@ usage: ${0##*/} /path/to/save/blocklist"
 #
 # $1 is a file or STDIN.
 prepare_domains() {
-  CR="$(printf -- '\r')"
-  TAB="$(printf -- '\t')"
-  readonly CR TAB
+	CR="$(printf -- '\r')"
+	TAB="$(printf -- '\t')"
+	readonly CR TAB
 
-  # TODO: perhaps replace this section with perl or something with a
-  # more capable pattern engine. domains could be matched in the initial
-  # pattern, but would need lookaround (hyphens are a valid part of
-  # domain nodes, but not at the beginning or end). by matching exactly
-  # what we want, it should alleviate the need to filter with 'grep -v'
-  grep -E -- "^(0\.0\.0\.0|127\.0\.0\.1)( |${TAB})+" "$1" \
-    | grep -v -- 'localhost$'                             \
-    | sed -E -e "s/${CR}//g" -e "s/( |${TAB})+/${TAB}/"
+	# TODO: perhaps replace this section with perl or something with a
+	# more capable pattern engine. domains could be matched in the initial
+	# pattern, but would need lookaround (hyphens are a valid part of
+	# domain nodes, but not at the beginning or end). by matching exactly
+	# what we want, it should alleviate the need to filter with 'grep -v'
+	grep -E -- "^(0\.0\.0\.0|127\.0\.0\.1)( |${TAB})+" "$1" \
+		| grep -v -- 'localhost$' \
+		| sed -E -e "s/${CR}//g" -e "s/( |${TAB})+/${TAB}/"
 }
 
 
@@ -62,44 +62,44 @@ prepare_domains() {
 #
 # $1 is a file or STDIN.
 format_domains() {
-  case "${DNS}" in
+	case "${DNS}" in
 
-    # there are two identical cut(1) invocations in the 'unwind' and
-    # 'unbound' patterns, but refactoring and moving them up into
-    # prepare_domains() means that cat(1) would need to be added to the
-    # 'unwind' pattern to handle STDIN.
-    'unwind')
-      cut -f 2 -- "$1"
+		# there are two identical cut(1) invocations in the 'unwind' and
+		# 'unbound' patterns, but refactoring and moving them up into
+		# prepare_domains() means that cat(1) would need to be added to the
+		# 'unwind' pattern to handle STDIN.
+		'unwind')
+			cut -f 2 -- "$1"
 
-      # https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
-      echo 'use-application-dns.net'
+			# https://support.mozilla.org/en-US/kb/canary-domain-use-application-dnsnet
+			echo 'use-application-dns.net'
 
-      ;;
+			;;
 
-    'unbound')
-      cut -f 2 -- "$1" | sed -- 's/.*/local-zone: "&" always_refuse/'
+		'unbound')
+			cut -f 2 -- "$1" | sed -- 's/.*/local-zone: "&" always_refuse/'
 
-      echo 'local-zone: "use-application-dns.net" always_refuse'
+			echo 'local-zone: "use-application-dns.net" always_refuse'
 
-      ;;
+			;;
 
-  esac | sort -u
+	esac | sort -u
 }
 
 
-[ -n "$1" ]                || usage
+[ -n "$1" ] || usage
 [ "$(uname)" = 'OpenBSD' ] || err "${0##*/} only supports OpenBSD."
-[ "$(id -u)" -eq 0 ]       || err "Execute ${0##*/} with root privileges."
+[ "$(id -u)" -eq 0 ] || err "Execute ${0##*/} with root privileges."
 
 
 if [ "$(rcctl get unwind flags)" != 'NO' ]; then
-  readonly DNS='unwind'
+	readonly DNS='unwind'
 
 elif [ "$(rcctl get unbound flags)" != 'NO' ]; then
-  readonly DNS='unbound'
+	readonly DNS='unbound'
 
 else
-  err "${0##*/} only supports unwind(8) and unbound(8)."
+	err "${0##*/} only supports unwind(8) and unbound(8)."
 
 fi
 
@@ -141,12 +141,12 @@ readonly TMP_BLOCKLIST
 readonly BLOCKLIST="$1"
 
 
-printf '%s\n' "${BLOCKLIST_URLS}"    \
-  | xargs -- ftp -o - -- 2>/dev/null \
-  | prepare_domains -                \
-  | format_domains -                 \
-  > "${TMP_BLOCKLIST}"               \
-  || err 'Unable to create blocklist.'
+printf '%s\n' "${BLOCKLIST_URLS}" \
+	| xargs -- ftp -o - -- 2>/dev/null \
+	| prepare_domains - \
+	| format_domains - \
+	> "${TMP_BLOCKLIST}" \
+	|| err 'Unable to create blocklist.'
 
 
 # if no blocklist is present, just create a blank template file so mv(1)
@@ -158,28 +158,25 @@ chmod -- 0444 "${BLOCKLIST}"
 mv -- "${BLOCKLIST}" "${BLOCKLIST}.bak"
 
 install -m 0444 -- "${TMP_BLOCKLIST}" "${BLOCKLIST}" \
-  || err "Unable to install(1) ${TMP_BLOCKLIST} to ${BLOCKLIST}"
+	|| err "Unable to install(1) ${TMP_BLOCKLIST} to ${BLOCKLIST}"
 
 
 case "${DNS}" in
-  'unwind')  unwind -n         && rcctl restart unwind  ;;
-  'unbound') unbound-checkconf && rcctl restart unbound ;;
-esac >/dev/null 2>&1 ||
+	'unwind') unwind -n && rcctl restart unwind ;;
+	'unbound') unbound-checkconf && rcctl restart unbound ;;
+esac >/dev/null 2>&1 || {
 
-{
+	# ${BLOCKLIST}.bak should always be a working file with appropriate
+	# permissions, so it is safe to move ${BLOCKLIST}.bak to
+	# ${BLOCKLIST} without further checks.
+	mv -- "${BLOCKLIST}.bak" "${BLOCKLIST}"
 
-  # ${BLOCKLIST}.bak should always be a working file with appropriate
-  # permissions, so it is safe to move ${BLOCKLIST}.bak to
-  # ${BLOCKLIST} without further checks.
-  mv -- "${BLOCKLIST}.bak" "${BLOCKLIST}"
-
-  # exits immediately without removing ${TMP_BLOCKLIST} and printing the
-  # file in the error message so it can be inspected.
-  err "${0##*/} failed to restart ${DNS}, which probably means ${DNS} didn't like ${TMP_BLOCKLIST}.
+	# exits immediately without removing ${TMP_BLOCKLIST} and printing the
+	# file in the error message so it can be inspected.
+	err "${0##*/} failed to restart ${DNS}, which probably means ${DNS} didn't like ${TMP_BLOCKLIST}.
 
 For now, either the previous working blocklist or a blank blocklist was
 instated at ${BLOCKLIST} with appropriate permissions."
-
 }
 
 # if the case statement above fails, the script exits before the removal
diff --git a/post-receive b/post-receive
--- a/post-receive
+++ b/post-receive
@@ -20,42 +20,42 @@ set -e
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 complain_tmpdir() {
-  err "Unable to create temporary directory at $1."
+	err "Unable to create temporary directory at $1."
 }
 
 
 handle_tmpfiles() {
-  rm -rf -- "${CLONE_DIR}" "${HTML_DIR}"
+	rm -rf -- "${CLONE_DIR}" "${HTML_DIR}"
 }
 
 
 # only called if working with website_md.
 gen_website() {
-    CLONE_DIR="$(mktemp -d)" || complain_tmpdir "${CLONE_DIR}"
-    HTML_DIR="$(mktemp -d)"  || complain_tmpdir "${HTML_DIR}"
-    readonly CLONE_DIR HTML_DIR
+	CLONE_DIR="$(mktemp -d)" || complain_tmpdir "${CLONE_DIR}"
+	HTML_DIR="$(mktemp -d)" || complain_tmpdir "${HTML_DIR}"
+	readonly CLONE_DIR HTML_DIR
 
-    git clone -- "${BARE_SRCDIR}" "${CLONE_DIR}"
+	git clone -- "${BARE_SRCDIR}" "${CLONE_DIR}"
 
-    "${HOME}/bin/ssg6" "${CLONE_DIR}" "${HTML_DIR}" "${WEBSITE##*//}" \
-      "${WEBSITE}" >/dev/null
+	"${HOME}/bin/ssg6" "${CLONE_DIR}" "${HTML_DIR}" "${WEBSITE##*//}" \
+		"${WEBSITE}" >/dev/null
 
-    rsync -a --delete --exclude='*.git' --exclude='*src/*' \
-      --exclude='.files' -- "${HTML_DIR}/" "${WEBDIR}/"
+	rsync -a --delete --exclude='*.git' --exclude='*src/*' \
+		--exclude='.files' -- "${HTML_DIR}/" "${WEBDIR}/"
 
-    "${HOME}/bin/rssg" "${CLONE_DIR}/index.md" \
-      "Newsletter - ${DESCRIPTION}" > "${WEBDIR}/rss.xml"
+	"${HOME}/bin/rssg" "${CLONE_DIR}/index.md" \
+		"Newsletter - ${DESCRIPTION}" > "${WEBDIR}/rss.xml"
 
-    # Temporary directories have 700 permissions by default. Without a
-    # chmod(1) here, the whole site will return 403 Forbidden after an
-    # rsync(1).
-    chmod 755 "${WEBDIR}"
+	# Temporary directories have 700 permissions by default. Without a
+	# chmod(1) here, the whole site will return 403 Forbidden after an
+	# rsync(1).
+	chmod 755 "${WEBDIR}"
 }
 
 
@@ -63,14 +63,14 @@ gen_website() {
 # then synchronize changes to ${SYSADM_DIR} so as to minimize
 # supervision/manual intervention.
 update_sysadm() {
-  readonly SYSADM_DIR='/etc/sysadm'
-  CLONE_DIR="$(mktemp -d)" || complain_tmpdir "${CLONE_DIR}"
-  readonly CLONE_DIR
+	readonly SYSADM_DIR='/etc/sysadm'
+	CLONE_DIR="$(mktemp -d)" || complain_tmpdir "${CLONE_DIR}"
+	readonly CLONE_DIR
 
-  git clone -- "${BARE_SRCDIR}" "${CLONE_DIR}"
+	git clone -- "${BARE_SRCDIR}" "${CLONE_DIR}"
 
-  rsync -a --delete --exclude='*.git' -- "${CLONE_DIR}/" "${SYSADM_DIR}/"
-  chmod 755 "${SYSADM_DIR}"
+	rsync -a --delete --exclude='*.git' -- "${CLONE_DIR}/" "${SYSADM_DIR}/"
+	chmod 755 "${SYSADM_DIR}"
 }
 
 
@@ -81,41 +81,41 @@ update_sysadm() {
 # replacing them each time the dotfiles repo is updated. the code as it
 # is now is merely an easy solution, not a fantastic one.
 update_ssg() {
-  readonly BINDIR="${HOME}/bin"
-  CLONE_DIR="$(mktemp -d)" || complain_tmpdir "${CLONE_DIR}"
-  readonly CLONE_DIR
+	readonly BINDIR="${HOME}/bin"
+	CLONE_DIR="$(mktemp -d)" || complain_tmpdir "${CLONE_DIR}"
+	readonly CLONE_DIR
 
-  git clone -- "${BARE_SRCDIR}" "${CLONE_DIR}"
+	git clone -- "${BARE_SRCDIR}" "${CLONE_DIR}"
 
-  install -g git -o git -m 700 -- \
-    "${CLONE_DIR}/.local/bin/rssg" "${BINDIR}/rssg"
+	install -g git -o git -m 700 -- \
+		"${CLONE_DIR}/.local/bin/rssg" "${BINDIR}/rssg"
 
-  install -g git -o git -m 700 -- \
-    "${CLONE_DIR}/.local/bin/ssg6" "${BINDIR}/ssg6"
+	install -g git -o git -m 700 -- \
+		"${CLONE_DIR}/.local/bin/ssg6" "${BINDIR}/ssg6"
 }
 
 
 # clone the repo and update the server information. generate the stagit
 # page and copy some misc files.
 clone_and_stagit() {
-  rm -rf -- "${STAGIT_DIR}"
-  mkdir -p -- "${STAGIT_DIR}"
-  git clone --bare -- "${BARE_SRCDIR}" "${STAGIT_DIR}/.git"
+	rm -rf -- "${STAGIT_DIR}"
+	mkdir -p -- "${STAGIT_DIR}"
+	git clone --bare -- "${BARE_SRCDIR}" "${STAGIT_DIR}/.git"
 
-  (cd "${STAGIT_DIR}/.git" && git update-server-info)
+	(cd "${STAGIT_DIR}/.git" && git update-server-info)
 
-  (cd "${STAGIT_DIR}" && stagit -- "${BARE_SRCDIR}")
+	(cd "${STAGIT_DIR}" && stagit -- "${BARE_SRCDIR}")
 
-  cp -f -- "${STAGIT_DIR}/log.html" "${STAGIT_DIR}/index.html"
-  cp -- "${WEBDIR}/stagit/style.css" "${STAGIT_DIR}/style.css"
+	cp -f -- "${STAGIT_DIR}/log.html" "${STAGIT_DIR}/index.html"
+	cp -- "${WEBDIR}/stagit/style.css" "${STAGIT_DIR}/style.css"
 }
 
 
 if [ -z "${PWD##*.git}" ]; then
-  readonly BARE_SRCDIR="${PWD}"
+	readonly BARE_SRCDIR="${PWD}"
 
 else
-  readonly BARE_SRCDIR="${PWD}/.git"
+	readonly BARE_SRCDIR="${PWD}/.git"
 
 fi
 
@@ -132,10 +132,10 @@ trap 'handle_tmpfiles' EXIT INT QUIT TERM
 
 
 case "${PWD##*/}" in
-  'website_md.git') readonly DESCRIPTION="${WEBSITE##*//}"                 ;;
-  'sysadm.git')     readonly DESCRIPTION='System Administration tools.'    ;;
-  'dotfiles.git')   readonly DESCRIPTION='My OpenBSD configuration files.' ;;
-  *)                err 'No description set for current repo.'             ;;
+	'website_md.git') readonly DESCRIPTION="${WEBSITE##*//}" ;;
+	'sysadm.git') readonly DESCRIPTION='System Administration tools.' ;;
+	'dotfiles.git') readonly DESCRIPTION='My OpenBSD configuration files.' ;;
+	*) err 'No description set for current repo.' ;;
 esac
 
 
@@ -146,10 +146,11 @@ echo "${WEBSITE}/src/${STAGIT_DIR##*/}/.git" > "${BARE_SRCDIR}/url"
 
 
 case "${PWD##*/}" in
-  'website_md.git') gen_website                                         ;;
-  'sysadm.git')     update_sysadm                                       ;;
-  'dotfiles.git')   update_ssg                                          ;;
-  *)                # if unrecognized, perform no repo specific actions ;;
+	'website_md.git') gen_website ;;
+	'sysadm.git') update_sysadm ;;
+	'dotfiles.git') update_ssg ;;
+	# if unrecognized, perform no repo specific actions
+	*) ;;
 esac
 
 
diff --git a/sudat b/sudat
--- a/sudat
+++ b/sudat
@@ -17,13 +17,13 @@
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 usage() {
-  err "Sync Upload Date and Access Time (sudat):
+	err "Sync Upload Date and Access Time (sudat):
 ${0##*/} [file_to_be_updated]
 
 Note that sudat extracts the upload date from .info.json files provided
@@ -33,77 +33,77 @@ extension."
 
 
 check_deps() {
-  while read -r dependency; do
+	while read -r dependency; do
 
-    [ -x "$(command -v -- "${dependency}")" ] \
-      || err "${dependency} not found in PATH or not executable."
+		[ -x "$(command -v -- "${dependency}")" ] \
+			|| err "${dependency} not found in PATH or not executable."
 
-  done
+	done
 }
 
 
 sudat() {
-  # file_extension parameter expansion will not work on files that have
-  # two extensions.
-  #
-  # however, since sudat-wrapper only points sudat at files with one
-  # extension, and since sudat handles the .info.json file separately,
-  # it's OK.
-  #
-  # sudat() works around this issue for .temp.{mkv,webm,mp4}
-  # files generated by yt-dlp.
-  file_extension="${1##*.temp}"
-  [ "${file_extension}" = "$1" ] && file_extension="${1##*.}"
-  file_template="${1%."${file_extension}"}"
+	# file_extension parameter expansion will not work on files that have
+	# two extensions.
+	#
+	# however, since sudat-wrapper only points sudat at files with one
+	# extension, and since sudat handles the .info.json file separately,
+	# it's OK.
+	#
+	# sudat() works around this issue for .temp.{mkv,webm,mp4}
+	# files generated by yt-dlp.
+	file_extension="${1##*.temp}"
+	[ "${file_extension}" = "$1" ] && file_extension="${1##*.}"
+	file_template="${1%."${file_extension}"}"
 
-  for file in "${file_template}"*; do
+	for file in "${file_template}"*; do
 
-    [ -f "${file}" ] || err "${file} isn't a file."
-    [ -w "${file}" ] || err "${file} isn't writable."
+		[ -f "${file}" ] || err "${file} isn't a file."
+		[ -w "${file}" ] || err "${file} isn't writable."
 
-  done
-
-
-  jsonfile="${file_template}.info.json"
-  [ -r "${jsonfile}" ] || err "${jsonfile} isn't readable."
+	done
 
 
-  timestamp="$(jq -er .upload_date "${jsonfile}")" \
-    || err "jq(1) failed on ${jsonfile}."
+	jsonfile="${file_template}.info.json"
+	[ -r "${jsonfile}" ] || err "${jsonfile} isn't readable."
 
 
-  # check if the timestamp is 8 digits (YYYYMMDD).
-  case "${timestamp}" in
-
-    [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) :                  ;;
-
-    *) err "${timestamp} isn't a correctly formatted timestamp." ;;
-
-  esac
+	timestamp="$(jq -er .upload_date "${jsonfile}")" \
+		|| err "jq(1) failed on ${jsonfile}."
 
 
-  # needed to match touch(1) format
-  timestamp="${timestamp}0000"
+	# check if the timestamp is 8 digits (YYYYMMDD).
+	case "${timestamp}" in
 
-  # update the timestamps of everything with the same naming
-  # convention.
-  touch -t "${timestamp}" "${file_template}"*
+		[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) : ;;
+
+		*) err "${timestamp} isn't a correctly formatted timestamp." ;;
+
+	esac
+
+
+	# needed to match touch(1) format
+	timestamp="${timestamp}0000"
+
+	# update the timestamps of everything with the same naming
+	# convention.
+	touch -t "${timestamp}" "${file_template}"*
 }
 
 
 while getopts q opt; do
-  case "${opt}" in
-    q) QUIET='yes' ;;
-    *) usage       ;;
-  esac
+	case "${opt}" in
+		q) QUIET='yes' ;;
+		*) usage ;;
+	esac
 done
 
 shift $((OPTIND - 1))
 
 
 [ -z "$1" ] && case "${QUIET}" in
-  'yes') exit  ;;
-  *)     usage ;;
+	'yes') exit	;;
+	*) usage ;;
 esac
 
 
diff --git a/update_graphs b/update_graphs
--- a/update_graphs
+++ b/update_graphs
@@ -17,13 +17,13 @@
 
 
 err() {
-  printf '%s\n' "$*" >&2
-  exit 1
+	printf '%s\n' "$*" >&2
+	exit 1
 }
 
 
 usage() {
-  err "${PROGRAM_NAME} [-s] [type] [period] [rrddir] [savedir]
+	err "${PROGRAM_NAME} [-s] [type] [period] [rrddir] [savedir]
 
 -s: swap colors for allowed incoming and outgoing traffic (by default,
     incoming traffic is green and outgoing traffic is blue). These defaults
@@ -48,27 +48,33 @@ statement in symux.conf would name them."
 # Restrict PERIOD length as to avoid too large an integer. 99999 hours is
 # roughly 11 years which is more than enough for my use case.
 check_period_length() {
-  [ ${#PERIOD} -gt 5 ] || err 'PERIOD is restricted to five characters or less.'
+	[ ${#PERIOD} -gt 5 ] || err 'PERIOD is restricted to five characters or less.'
 }
 
 
 gen_pf_graphs() {
-  [ "${SWAPCOLORS}" = 'yes' ] && INCOLOR="${BLUE}" OUTCOLOR="${GREEN}"
+	GRAPHS='pf-bits
+pf-passed-packets
+pf-dropped-packets
+pf-state-inserts-removals
+pf-state-searches'
 
-  : "${INCOLOR:=${GREEN}}"
-  : "${OUTCOLOR:=${BLUE}}"
+	[ "${SWAPCOLORS}" = 'yes' ] && INCOLOR="${BLUE}" OUTCOLOR="${GREEN}"
 
-
-  for graphname in 'pf-bits' 'pf-passed-packets' 'pf-dropped-packets' 'pf-state-inserts-removals' 'pf-state-searches'; do
-
-
-    BASE_CMD="rrdtool graph "${SAVEDIR}/${graphname}-${PERIOD}.png" -s -${HOURS}hours"
-
-    case "${graphname}" in
+	: "${INCOLOR:=${GREEN}}"
+	: "${OUTCOLOR:=${BLUE}}"
 
 
-      'pf-bits')
-        REST_OF_CMD="-t 'pf bits in/out (IPv4)' \
+	for graphname in ${GRAPHS}; do
+
+
+		BASE_CMD="rrdtool graph "${SAVEDIR}/${graphname}-${PERIOD}.png" -s -${HOURS}hours"
+
+		case "${graphname}" in
+
+
+			'pf-bits')
+				REST_OF_CMD="-t 'pf bits in/out (IPv4)' \
 --vertical-label 'bits/s' \
 'DEF:bytes_v4_in=${RRDDIR}/${TYPE}.rrd:bytes_v4_in:MAX' \
 'DEF:bytes_v4_out=${RRDDIR}/${TYPE}.rrd:bytes_v4_out:MAX' \
@@ -77,75 +83,75 @@ gen_pf_graphs() {
 'AREA:bps_in${INCOLOR}:in' \
 'AREA:bps_out${OUTCOLOR}:out'"
 
-        ;;
+				;;
 
 
-      'pf-passed-packets')
-        REST_OF_CMD="-t 'pf passed packets in/out (IPv4)' \
+			'pf-passed-packets')
+				REST_OF_CMD="-t 'pf passed packets in/out (IPv4)' \
 --vertical-label 'packets/s' \
 'DEF:packets_v4_in_pass=${RRDDIR}/${TYPE}.rrd:packets_v4_in_pass:MAX' \
 'DEF:packets_v4_out_pass=${RRDDIR}/${TYPE}.rrd:packets_v4_out_pass:MAX' \
 'AREA:packets_v4_in_pass${INCOLOR}:in' \
 'AREA:packets_v4_out_pass${OUTCOLOR}:out'"
 
-        ;;
+				;;
 
 
-      'pf-dropped-packets')
-        REST_OF_CMD="-t 'pf dropped packets in/out (IPv4)' \
+			'pf-dropped-packets')
+				REST_OF_CMD="-t 'pf dropped packets in/out (IPv4)' \
 --vertical-label 'packets/s' \
 'DEF:packets_v4_in_drop=${RRDDIR}/${TYPE}.rrd:packets_v4_in_drop:MAX' \
 'DEF:packets_v4_out_drop=${RRDDIR}/${TYPE}.rrd:packets_v4_out_drop:MAX' \
 'AREA:packets_v4_in_drop${RED}:in' \
 'AREA:packets_v4_out_drop${YELLOW}:out'"
 
-        ;;
+				;;
 
 
-      'pf-state-inserts-removals')
-        REST_OF_CMD="-t 'pf state inserts/removals' \
+			'pf-state-inserts-removals')
+				REST_OF_CMD="-t 'pf state inserts/removals' \
 --vertical-label 'states/s' \
 'DEF:states_inserts=${RRDDIR}/${TYPE}.rrd:states_inserts:MAX' \
 'DEF:states_removals=${RRDDIR}/${TYPE}.rrd:states_removals:MAX' \
 'AREA:states_inserts${GREEN}:inserts' \
 'AREA:states_removals${RED}:removals'"
 
-        ;;
+				;;
 
 
-      'pf-state-searches')
-        REST_OF_CMD="-t 'pf state searches' \
+			'pf-state-searches')
+				REST_OF_CMD="-t 'pf state searches' \
 --vertical-label 'states/s' \
 'DEF:states_searches=${RRDDIR}/${TYPE}.rrd:states_searches:MAX' \
 'AREA:states_searches${RED}:searches'"
 
-        ;;
+				;;
 
 
-      *)
-        err 'This should never happen.'
+			*)
+				err 'This should never happen.'
 
-        ;;
-
-
-    esac
-
-    eval "${BASE_CMD} ${REST_OF_CMD}"
+				;;
 
 
-  done
+		esac
+
+		eval "${BASE_CMD} ${REST_OF_CMD}"
+
+
+	done
 }
 
 
 [ -x "$(command -v -- 'rrdtool')" ] \
-  || err "rrdtool not found in PATH or not executable."
+	|| err "rrdtool not found in PATH or not executable."
 
 
 while getopts s opt; do
-  case "${opt}" in
-    's') SWAPCOLORS='yes' ;;
-    *)   usage            ;;
-  esac
+	case "${opt}" in
+		's') SWAPCOLORS='yes' ;;
+		*) usage ;;
+	esac
 done
 
 shift $((OPTIND - 1))
@@ -162,18 +168,18 @@ readonly SAVEDIR="$4"
 
 
 case "${TYPE}" in
-  'pf') :                                                           ;;
-  *)    err "\"${TYPE}\" isn't a valid type of statistic to graph." ;;
+	'pf') :	;;
+	*) err "\"${TYPE}\" isn't a valid type of statistic to graph." ;;
 esac
 
 
 # shellcheck disable=SC2086
 case "${PERIOD}" in
-  'day')   readonly HOURS=24                                           ;;
-  'week')  readonly HOURS=168                                          ;;
-  'month') readonly HOURS=672                                          ;;
-  [0-9]*)  check_period_length; readonly HOURS=${PERIOD}               ;;
-  *)       err "\"${PERIOD}\" isn't a valid time period for graphing." ;;
+	'day') readonly HOURS=24 ;;
+	'week')	readonly HOURS=168 ;;
+	'month') readonly HOURS=672 ;;
+	[0-9]*)	check_period_length; readonly HOURS=${PERIOD} ;;
+	*) err "\"${PERIOD}\" isn't a valid time period for graphing." ;;
 esac
 
 
@@ -196,5 +202,5 @@ readonly BLUE='#0000FF'
 
 
 case "${TYPE}" in
-  'pf') gen_pf_graphs "$1" "$2" "$3" "$4" ;;
+	'pf') gen_pf_graphs "$1" "$2" "$3" "$4" ;;
 esac
