genblock: these variables can vary between executions, i.e. are not constant, so they become lowercase.

diff --git a/genblock b/genblock
--- a/genblock
+++ b/genblock
@@ -43,11 +43,11 @@ rotate_old_blocklist() {
   # if no blocklist, just create a blank template file so mv(1) is
   # guaranteed to have something to move and ${blocklist}.bak is
   # guaranteed to exist.
-  [ -f "${BLOCKLIST}" ] || :>"${BLOCKLIST}"
+  [ -f "${blocklist}" ] || :>"${blocklist}"
 
-  chmod -- 0444 "${BLOCKLIST}"
+  chmod -- 0444 "${blocklist}"
 
-  mv -- "${BLOCKLIST}" "${BLOCKLIST}.bak"
+  mv -- "${blocklist}" "${blocklist}.bak"
 }
 
 
@@ -78,7 +78,7 @@ prepare_domains() {
 #
 # $1 is a file or STDIN.
 format_domains() {
-  case "${DNS}" in
+  case "${dns}" in
 
     # there are two identical cut(1) invocations in the 'unwind' and
     # 'unbound' patterns, but refactoring and moving them up into
@@ -114,8 +114,8 @@ format_domains() {
 # we are running as root, but if it does crop up the path of the
 # temporary blocklist should be returned to the user.
 install_new_blocklist() {
-  if ! install -m 0444 -- "${TMP_BLOCKLIST}" "${BLOCKLIST}"; then
-    err "Unable to install(1) ${TMP_BLOCKLIST} to ${BLOCKLIST}"
+  if ! install -m 0444 -- "${tmp_blocklist}" "${blocklist}"; then
+    err "Unable to install(1) ${tmp_blocklist} to ${blocklist}"
   fi
 }
 
@@ -123,7 +123,7 @@ install_new_blocklist() {
 # check that the configuration file is valid. if it is, restart the DNS
 # server.
 restart_dns() {
-  case "${DNS}" in
+  case "${dns}" in
     'unwind')  unwind -n         && rcctl restart unwind  ;;
     'unbound') unbound-checkconf && rcctl restart unbound ;;
     *)         complain_dns                               ;;
@@ -136,14 +136,14 @@ restore_backup_blocklist() {
   # due to the way rotate_old_blocklist() works, ${blocklist}.bak should
   # always be a working file with appropriate permissions, so it is safe
   # to move ${blocklist}.bak to ${blocklist} without further checks.
-  mv -- "${BLOCKLIST}.bak" "${BLOCKLIST}"
+  mv -- "${blocklist}.bak" "${blocklist}"
 
   # exits immediately without removing ${tmp_blocklist} and printing the
   # file in the error message so it can be inspected.
-  err "restart_dns() failed, which probably means ${DNS}(8) didn't like ${TMP_BLOCKLIST}.
+  err "restart_dns() failed, which probably means ${dns}(8) didn't like ${tmp_blocklist}.
 
 For now, either the previous working blocklist or a blank blocklist was
-instated at ${BLOCKLIST} with appropriate permissions."
+instated at ${blocklist} with appropriate permissions."
 }
 
 
@@ -151,20 +151,20 @@ instated at ${BLOCKLIST} with appropriate permissions."
 must_be_root
 
 if [ "$(rcctl get unwind flags)" != 'NO' ]; then
-  readonly DNS='unwind'
-  readonly BLOCKLIST='/etc/blocklist.unwind'
+  readonly dns='unwind'
+  readonly blocklist='/etc/blocklist.unwind'
 
 elif [ "$(rcctl get unbound flags)" != 'NO' ]; then
-  readonly DNS='unbound'
-  readonly BLOCKLIST='/etc/blocklist.unbound'
+  readonly dns='unbound'
+  readonly blocklist='/etc/blocklist.unbound'
 
 else
   complain_dns
 
 fi
 
-TMP_BLOCKLIST="$(mktemp)"
-readonly TMP_BLOCKLIST
+tmp_blocklist="$(mktemp)"
+readonly tmp_blocklist
 
 readonly BLOCKLIST_URLS='/etc/sysadm/blocklist_urls'
 
@@ -174,7 +174,7 @@ xargs -- ftp -o - -- 2>/dev/null \
   < "${BLOCKLIST_URLS}"          \
   | prepare_domains -            \
   | format_domains -             \
-  > "${TMP_BLOCKLIST}"           \
+  > "${tmp_blocklist}"           \
   || err 'Unable to create blocklist.'
 
 rotate_old_blocklist
@@ -184,4 +184,4 @@ restart_dns >/dev/null 2>&1 || restore_backup_blocklist
 
 # if restore_backup_blocklist() is called, it exits before the removal
 # so the temporary blocklist is kept.
-rm -- "${TMP_BLOCKLIST}"
+rm -- "${tmp_blocklist}"
