genblock: code restructuring.
backup()          -> handle_old_blocklist()
install_blocklist -> install_new_blocklist()

handle_old_blocklist() refactored to make for a simpler, more
straightforward revert()

install_new_blocklist replaces a set of two calls to cp(1) into chmod(1)
with one call to install(1).

diff --git a/genblock b/genblock
--- a/genblock
+++ b/genblock
@@ -37,14 +37,15 @@ EOF
 
 fi
 
-backup() {
-  if [ -f "${blocklist}" ]; then
-    mv -- "${blocklist}" "${blocklist}.bak"
+handle_old_blocklist() {
+  # if no blocklist, just create a blank template file so mv(1) is
+  # guaranteed to have something to move and ${blocklist}.bak is
+  # guaranteed to exist for revert().
+  [ -f "${blocklist}" ] || :>"${blocklist}"
 
-  else
-    return 0
+  chmod -- 0444 "${blocklist}"
 
-  fi
+  mv -- "${blocklist}" "${blocklist}.bak"
 }
 
 # filter out localhost definitions in hosts files and grab the lines
@@ -99,11 +100,11 @@ format_domains() {
   esac | dos2unix | sort | uniq
 }
 
-# copy the temporary blocklist to the destination and make it world
-# readable.
-install_blocklist() {
-  cp -- "${tmp_blocklist}" "${blocklist}"
-  chmod -- 0444 "${blocklist}"
+# copy the temporary blocklist to the destination.
+install_new_blocklist() {
+  if ! install -m 0444 -- "${tmp_blocklist}" "${blocklist}"; then
+    err "Unable to install(1) ${tmp_blocklist} to ${blocklist}"
+  fi
 }
 
 # check that the configuration file is valid. if it is, restart the DNS
@@ -116,18 +117,18 @@ restart_dns() {
   esac
 }
 
-# called if restart_dns() fails. if a backup file exists, restore it.
-# otherwise, remove the blocklist and create an empty world readable
-# file in its place.
 revert() {
-  if [ -f "${blocklist}.bak" ]; then
-    mv -- "${blocklist}.bak" "${blocklist}"
+  # due to the way handle_old_blocklist() works, ${blocklist}.bak should
+  # always be a working file with appropriate permissions, so it is safe
+  # to move ${blocklist}.bak to ${blocklist} without further checks.
+  mv -- "${blocklist}.bak" "${blocklist}"
 
-  else
-    :>"${blocklist}"
-    chmod -- 0444 "${blocklist}"
+  # exits immediately without removing ${tmp_blocklist} and printing the
+  # file in the error messageso it can be inspected.
+  err "restart_dns() failed, which probably means ${dns}(8) didn't like ${tmp_blocklist}.
 
-  fi
+For now, either the previous working blocklist or a blank blocklist was
+instated at ${blocklist} with appropriate permissions."
 }
 
 prereqs() {
@@ -164,7 +165,9 @@ xargs ftp -o - -- 2>/dev/null \
   > "${tmp_blocklist}"        \
   || err 'Unable to create blocklist.'
 
-backup                      || err 'Unable to backup blocklist file.'
-install_blocklist           || err 'Unable to install blocklist.'
+handle_old_blocklist
+install_new_blocklist
+
 restart_dns >/dev/null 2>&1 || revert
-rm -- "${tmp_blocklist}"    || err "Unable to remove ${tmp_blocklist}."
+
+rm -- "${tmp_blocklist}"
