sudat only handles one file at a time. no more soft errors. sudatwrapper is parallelized (NCPU - 1 processes)

diff --git a/sudat b/sudat
--- a/sudat
+++ b/sudat
@@ -22,12 +22,6 @@ err() {
 }
 
 
-soft_err() {
-  printf '%s\n' "$*" >&2
-  return 1
-}
-
-
 usage() {
   err "Sync Upload Date and Access Time (sudat):
 ${0##*/} [file_to_be_updated]
@@ -53,27 +47,27 @@ handle_date() {
   extension="${file_to_be_updated##*.}"
   for file in "${file_to_be_updated%."${extension}"}"*; do
 
-    [ -f "${file}" ] || soft_err "${file} isn't a file; skipping."
-    [ -w "${file}" ] || soft_err "${file} isn't writable; skipping."
+    [ -f "${file}" ] || err "${file} isn't a file."
+    [ -w "${file}" ] || err "${file} isn't writable."
 
   done
 
 
   jsonfile="${file_to_be_updated%."${extension}"}.info.json"
-  [ -f "${jsonfile}" ] || soft_err "${jsonfile} isn't a file; skipping."
-  [ -r "${jsonfile}" ] || soft_err "${jsonfile} isn't readable; skipping."
+  [ -f "${jsonfile}" ] || err "${jsonfile} isn't a file."
+  [ -r "${jsonfile}" ] || err "${jsonfile} isn't readable."
 
 
   timestamp="$(jq -er .upload_date "${jsonfile}")" \
-    || soft_err "jq(1) failed on ${jsonfile}; skipping."
+    || err "jq(1) failed on ${jsonfile}."
 
 
   # check if the timestamp is 8 digits (YYYYMMDD).
   case "${timestamp}" in
 
-    [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) :                     ;;
+    [0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]) :      ;;
 
-    *) soft_err "${timestamp} isn't correctly formatted; skipping." ;;
+    *) err "${timestamp} isn't correctly formatted." ;;
 
   esac
 
@@ -88,10 +82,8 @@ handle_date() {
 }
 
 
-[ -z "$*" ] && usage
+[ -z "$1" ] && usage
 echo 'jq' | check_deps
 
 
-for argument in "$@"; do
-  handle_date "${argument}" &
-done
+handle_date "$1"
